### ISSUE TITLE
Repeatable items render at the bottom of the dialog

### ISSUE THREAD

**Issue by jc1001** [aurelia/dialog#75]
Hi there,

It seems that elements that is bound to a repeat.for is not rendering in the correct location.  To illustrate this problem I've extended the person object in the readme example as follows:
```javascript
person = { firstName: 'Wade', middleName: 'Owen', lastName: 'Watts' };
```
changed to:
```javascript
person = { firstName: 'Wade', middleName: 'Owen', lastName: 'Watts', friends: ["John", "Jane", "Joe"] };
```
I've changed the dialog template to this:
```javascript
<template>
	<ai-dialog>

		<ai-dialog-body>
			<div style="background-color:red;height:20px;">Top</div>
			<div repeat.for="friend of person.friends" style="background-color:blue;">
				<span>${friend}</span>
			</div>
			<div style="background-color:yellow;height:20px;">Bottom</div>
		</ai-dialog-body>

		<ai-dialog-footer>
			<button click.trigger="controller.cancel()">Cancel</button>
			<button click.trigger="controller.ok(person)">Ok</button>
		</ai-dialog-footer>
	</ai-dialog>
</template>
```
When the dialog is displayed, it looks like this:
![renderresultsdialog](https://cloud.githubusercontent.com/assets/15125812/11692215/25e0304c-9ea7-11e5-8dc5-bedeacdf3524.PNG)

To confirm that I'm not doing something wrong, I took the divs from the dialog body and pasted them into a normal view.  It rendered as expected:
![renderresultscorrect](https://cloud.githubusercontent.com/assets/15125812/11692259/56ec1eee-9ea7-11e5-887d-ed3a0544eb16.PNG)

**Comment by PWKad** [comment]
This could be due to a repeater rendered directly inside of a content selector.  For now can you wrap your elements listed in a block-style element (such as a div) and see if that resolves the issue?  We will be upgrading the content selector to the current spec so odds of resolving this issue if it is indeed that are probably lower priority then fixing it in the update spec implementation.

**Comment by EisenbergEffect** [comment]
There's a bug in the templating engine that I resolved yesterday that could also be causing this. We'll push out a new release soon and then we can check if it's resolved.

**Comment by jc1001** [comment]
Thanks for the feedback.  When wrapping the repeater logic in another div (as suggested), it works fine.  I eventually had to go that route anyway (div with overflow), since the list of items that I am displaying was becoming too large.

**Comment by PWKad** [comment]
@jc1001 This should be fixed on latest can you confirm the issue is resolved before I close it?

**Comment by jc1001** [comment]
Still does not seem to be working.  I did run 'jspm update' to confirm that I have the latest updates.  I've attached a sample (modified starter project) to illustrate the problem.  Please let me know if you require anything else.
[ES2016.zip](https://github.com/aurelia/dialog/files/77325/ES2016.zip)

**Comment by PWKad** [comment]
@jc1001 Thanks for the repro!  I did verify that wrapping the content in a block-style element should be a workaround you can use for now while we look in to this further.

@EisenbergEffect I think my first guess was correct, if you wrap the content of the body in a block-style element such as a div everything works properly because the div acts as the anchor instead of the surrounding template (which is a custom element with a content selector)

**Comment by PWKad** [comment]
@jc1001 This should be fixed int he latest release of templating.  Just confirmed with your repro and upgrading to latest releases - 

![image](https://cloud.githubusercontent.com/assets/4238393/12632810/6292a28c-c520-11e5-9fb5-a62a2a402a79.png)
