### ISSUE TITLE
Dialog not closed when browser back button is used

### ISSUE THREAD

**Issue by henning-krause** [aurelia/dialog#96]
Started with the skeleton-navigation app and added aurelia-dialog.

Added this import to the top of the welcome.js file:
```js
import {DialogService} from 'aurelia-dialog';
import {Prompt} from 'aurelia-dialog/./examples/prompt';
```

And this submit handler, taken from the Aurelia-Dialog documentation page:

```js
  submit() {
      this.dialogService.open({ viewModel: Prompt, model: 'Good or Bad?'}).then(response => {
      if (!response.wasCancelled) {
        console.log('good');
      } else {
        console.log('bad');
      }
      console.log(response.output);
    });
```

Repro:
1. Open the web page
2. Click on Github Users
3. Click on Welcome
4. Click Submit. The dialog is opened.
5. Click on the Back button of the browser.

Effect:
The "Github User" page is displayes again, but the dialog is still open.

Any ideas on how to solve this?

**Comment by PWKad** [comment]
Good question, let me take a look and think about it.  Thanks for the repro steps!

**Comment by piwnik** [comment]
While this issue isn't solved, is there any way to close dialog from parent? Or check if any dialog is shown (without tracking this by myself)? Then we probably can on parent canDeactivate check is the dialog shown, if yes - return false, but close dialog, and on second 'back' return true.

**Comment by piwnik** [comment]
@henning-krause I solve this issue by adding ['autorize' router pipeline step](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/securing-your-app).

```javascript
run(routingContext: NavigationInstruction, next) {

		// HACK closing dialog before navigate away from view
		var controller = this.dialogService.renderer.dialogControllers[0];

		if (controller) {
			controller.cancel();
			return next.cancel(new Redirect(routingContext.router.history.previousLocation, {trigger:false, replace: false}));
		}

		// HACKend
	
		return next();
}
````

Where if dialog is open - close it and stay on same page.

If you need only close dialog and continue navigation, just remove redirection line (which recovers history step)
```javascript
return next.cancel(new Redirect(routingContext.router.history.previousLocation, {trigger:false, replace: false}));

```

It's dirty hack, but I hope it solve your issue until real legal solution will be implemented by Aurelia team

**Comment by PWKad** [comment]
Yeah I was looking at this again this morning and trying to imagine the best way to approach the issue.  Since promises aren't cancellable I am leaning towards passing a function as an optional argument in to the `dialogService.open` call but it seems brittle also.  Any suggestions welcome.

**Comment by piwnik** [comment]
I think passing callback to `dialogService.open ` and handling navigation on every viewModel is annoying.

What if dialog plugin add router pipeline step by them self? In [router pipeline provider](https://github.com/aurelia/router/blob/master/src/pipeline-provider.js) add some slot to do that earlier than 'authorize' step and handle this case automatically.

Of course I understand, that dialog plugin shall not have dependencies, but maybe then create some 'router friendly dialog plugin' which will have dependencies on aurelia-router, aurelia-dialog and do that dirty job for us? 

Or have dependency on EventAggregator and handling this issue by caching/handling routing events?

Yes, I also don't like these solutions, but maybe they will force for some brilliant idea :)

**Comment by jedd-ahyoung** [comment]
@PWKad I've just submitted a pull request for the dialog service - it keeps a collection of all of the open controllers. With this, I implemented a "hasActiveDialog" function. With this, we could easily iterate over the open modal dialogs and close them all. This would probably work, right?

Alternatively, one could cancel navigation by using `hasActiveDialog` with the `deactivate` lifecycle.

**Comment by PWKad** [comment]
@jedd-ahyoung seems reasonable although I'm still not sold that the standard experience should be to close by default, I'm still wondering if the consumer is wanting more than one open modal if it makes more sense for them to add their own pipeline step.

As @piwnik mentioned if the user wants to add a pipeline step this should now be achievable by iterating over the open dialogs and closing them correct?

**Comment by ns6482** [comment]
@jedd-ahyoung ,with ref to the `hasActiveDialog`and deactivate lifecycle, so you staying that each view model would check if dialog is active. So would this go in canActivate? If you want all vm's to check this could there be a way without repeating code?

**Comment by valichek** [comment]
@PWKad 
Maybe the following approach will work. We just need to get the reference to dialog controller in some way. The most obvious is to change the way how `open()` works. It could return the promise for dialog controller, we save it somewhere on open and get result using controller property

```javascript
this.dialogPromise = this.dialogService.open(...)
this.dialogPromise.then((dialogController) => {
  return dialogController.resultPromise;
}).then((response) => {
  // we get result here
   if (!response.wasCancelled) {
        console.log('good');
      } else {
        console.log('bad');
      }
      console.log(response.output);
});
```

and on `deactivate()` we return promise for closing

```javascript
// inside deactivate
return this.dialogPromise.then((dialogController) => {
  return dialogController.close()
})
```

**Comment by EisenbergEffect** [comment]
The suggested API makes normal usage awkward in order to facilitate an edge case. I think it makes more sense for the promise to resolve to a result. However, we could do something similar to what we do with HttpClient and simply add a property onto the promise itself which would provide the controller.

```
let promise = this.dialogService.open(...);
let controller = promise.dialogController; //the dialog controller; just added as a simple property
```

**Comment by valichek** [comment]
@EisenbergEffect I agree that promise property is simpler approach, but navigating is not edge case and should be handled somehow, IMO it's bug

**Comment by EisenbergEffect** [comment]
This is two separate issues. In my comment above, I'm concerned about the API of open method. I believe that once that's solved, by combining that with the property that @jedd-ahyoung as already provided, you should be able to handle the navigation scenario as well.

**Comment by valichek** [comment]
@EisenbergEffect I'm writing popover-like aurelia component now and use ideas provided with aurelia-dialog. I consider aurelia-dialog as a special case for popover that really does make sense, because the only difference is in the target to render it. And I see that it's not possible (?) to expose the controller or even promise for it, because it is created and initialized inside the promise because it has references to resolve of the result. We cannot expose smth that doesn't exist and/or initialized. And if we try to use `this.dialogControllers` to close all the present dialogs there is always possibility that one dialog is still initializing - it's async stuff, so you cannot be sure if content of `this.dialogControllers` won't be changed in a while.

**Comment by stsje** [comment]
Will this issue be labeled a bug, or will we have to implement closing the dialogs ourselves?
We don't feel like "wasting" time on implementing a hack, if it's something you'll resolve in the plugin.

**Comment by EisenbergEffect** [comment]
Not everyone wants the back button to close a dialog. There are definite scenarios where this is not desirable. So, it's definitely not a bug.

We could add a new feature that enables the back button to cancel a dialog, but this would have to be done carefully because there's no way to detect a back button click. You can only detect a navigation and try to extrapolate whether or not it was a back action. We are working on adding this "extrapolation" code to the router in the future, but it's not there yet. Assuming it was there, this would require interop with the router, but we can't hard couple the dialog to the router since they should be usable independently. 

If you would like to propose a solution for adding the option with some various hooks, we would be happy to accept a PR. Perhaps it's as simple as a router pipeline step that simply closes any open dialogs on navigation? Such a step could be included in our documentation on the router and/or the dialog.

**Comment by EisenbergEffect** [comment]
I think we are addressing this issue via the new external access to the controller, which allows closing the  dialog on demand from the "outside". This enables developers to choose if they want to close dialogs on navigation or not.

**Comment by valichek** [comment]
@EisenbergEffect What new external access to the controller do you mean? Is it implemented? Could you provide some example?

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung should be able to provide more details on that.

**Comment by Vaccano** [comment]
@EisenbergEffect, @jedd-ahyoung - I know it has been over a year since the call for an example was made, but this is still relevant (to me).

An example would be helpful.

**Comment by StrahilKazlachev** [comment]
@Vaccano What example do you need? How to get a `DialogController`, how to use a `DialogController`, how to close all currently open dialogs, ...?

**Comment by Vaccano** [comment]
I was hoping for an example on how to use the Controller, but it is largely academic for me now as I think I found [another way to solve my problem](https://stackoverflow.com/a/46209504/16241).

At this point I am curious, but don't need it.  So don't worry about it if it is not easy to make.

**Comment by abowen** [comment]
I'm assuming that the following is the best way to go about clearing any dialogs when navigating away?

```
    function step() {
      return step.run;
    }
    step.run = (navigationInstruction, next) => {
      if (this.dialogService.hasActiveDialog) {
        this.dialogService.closeAll();
      }
      return next();
    };
    config.addPreActivateStep(step);
```
